<Project>
  <Import Project="Versions.props" />
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <EnablePackageVersionOverride>true</EnablePackageVersionOverride>
    <AspireVersion>13.5.3</AspireVersion>
  </PropertyGroup>
  <ItemGroup Label="ASP.NET Core">
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="DistributedLock.Redis" Version="1.1.1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageVersion Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageVersion Include="Mediator.SourceGenerator" Version="3.0.2" />
    <PackageVersion Include="MessagePack" Version="3.1.8" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.9.0" />
    <PackageVersion Include="Microsoft.Extensions.VectorData.Abstractions" Version="10.9.0" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="System.Net.Http.Json" Version="10.0.11" />
    <PackageVersion Include="System.Text.Json" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup Label="Entity Framework Core and Database">
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
  </ItemGroup>
  <ItemGroup Label="API Documentation-Versioning">
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.3" />
    <PackageVersion Include="Asp.Versioning.Http" Version="10.2.3" />
    <PackageVersion Include="Asp.Versioning.Http.Client" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup Label="Libraries - Utilities">
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Humanizer.Core" Version="3.0.10" />
    <PackageVersion Include="Scrutor" Version="6.1.0" />
  </ItemGroup>
  <ItemGroup Label="Aspire">
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="9.5.1-preview.1.25502.11" />
    <PackageVersion Include="Aspire.Hosting.Kubernetes" Version="9.5.1-preview.1.25502.11" />
    <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
    <PackageVersion Include="Scalar.Aspire" Version="0.3.2" />
    <PackageVersion Include="Aspire.Hosting.Qdrant" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.5.3" />
    <PackageVersion Include="Aspire.Qdrant.Client" Version="13.5.3" />
    <PackageVersion Include="Aspire.StackExchange.Redis" Version="13.5.3" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.5.0" />
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.McpInspector" Version="13.5.0" />
  </ItemGroup>
  <ItemGroup Label="OpenTelemetry">
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.12.0-beta.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.18.0-beta.1" />
  </ItemGroup>
  <ItemGroup Label="AI">
    <!-- SemanticKernel-->
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.Chroma" Version="1.74.0-alpha" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.InMemory" Version="1.74.0-preview" />
    <PackageVersion Include="Microsoft.SemanticKernel.Connectors.Qdrant" Version="1.74.0-preview" />
    <!-- `Microsoft.Agents.AI` implicity has reference to `Microsoft.Extensions.AI` for chatcompletion and embedding-->
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.20.0" />
    <!-- Azure implementation for `Microsoft.Extensions.AI` abstrations -->
    <PackageVersion Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <!-- Ollama implementation for `Microsoft.Extensions.AI` abstrations -->
    <PackageVersion Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.5.0" />
    <!-- OpenAI implementation for `Microsoft.Extensions.AI` abstrations -->
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
    <!-- MCP-->
    <PackageVersion Include="ModelContextProtocol" Version="2.2.0" />
    <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <!-- A2A-->
    <PackageVersion Include="Microsoft.Agents.AI.A2A" Version="1.20.0-preview.260831.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting.A2A.AspNetCore" Version="1.20.0-preview.260831.1" />
  </ItemGroup>
</Project>
