<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>GenAIEshop.BuildingBlocks.UnitTests</AssemblyName>
    <RootNamespace>GenAIEshop.BuildingBlocks.UnitTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Shared\Tests.Shared\Tests.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.VisualStudio.TestPlatform" />
    <PackageReference Include="xunit.v3.core.mtp-v2" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
